Matrix_subtraction.cpp
=> Matrix subtraction in c++

Sieve_of_Erastosthenes_(sum_of_primes_tiill_N).cpp, segment_tree_class_implementation.cpp
This code finds all the primes till N and also computes the summation of those primes.
=> Added Sieve of Erastosthenes in C++

jump_search_array.cpp
=> added jump search

tower_of_hanoi.cpp
DSA TOWER OF HANOI Solution added (Hactober feast)
=> DSA Tower of henoi solution added

Insertionsort.cpp
I have added Insertion Sort Algo
=>  Added Insertion Sort

fibonacci.cpp
I have added Fibonacci series using recursion
=> Fibonacci Series using Recursion

DP/LongestPalidromicSubstring.cpp
Added Longest Palidromic Substring dp solution for (hacktoberfest)
=> Added Longest Palidromic Substring dp solution

maxheap.cpp
=> added max_heap code

DP/edit_distance.cpp
This code is the solution for the famous DP (Dynamic Programming) problem "Edit Distance" in c++.
=> Added C++ Code for Edit Distance Problem

DSA in CPP/Array Adt/All_together_in_CPP.cpp, DSA in CPP/Array Adt/Array_ADT.cpp, DSA in CPP/Array Adt/BinarySearch.cpp, DSA in CPP/Array Adt/If_array_is_sorted.cpp, DSA in CPP/Array Adt/Insert_and_Append.cpp, DSA in CPP/Array Adt/LinearSearch.cpp, DSA in CPP/Array Adt/Reversing_an_array.cpp, DSA in CPP/Array Adt/delete.cpp, DSA in CPP/Linked List/count_and_sum.cpp, DSA in CPP/Linked List/display.cpp, DSA in CPP/Recursion/Static_Global.cpp, DSA in CPP/Recursion/Toer_Of_HAnoi.cpp, DSA in CPP/Recursion/combination_using_pascal_triangle.cpp, DSA in CPP/Recursion/factorial.cpp, DSA in CPP/Recursion/fibonacci.cpp, DSA in CPP/Recursion/tree_recrursion.cpp
Contributed my own DSA codes in c++ covering Recursion, Array Adt, Linked List
=> DSA codes in c++

Rotton_Oranges.cpp
You are given an m x n grid where each cell can have one of three values:
0 representing an empty cell,
1 representing a fresh orange, or
2 representing a rotten orange.
Every minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten.
Return the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.
=> Rotton_Oranges.cpp

Kth-Permutation_Sequence.cpp
The set [1, 2, 3, ..., n] contains a total of n! unique permutations.
By listing and labeling all of the permutations in order, we get the following sequence for n = 3:
"123"
"132"
"213"
"231"
"312"
"321"
=> Kth-Permutation_Sequence

Palindrome_Partitioning.cpp
Problem Statement: You are given a string s, partition it in such a way that every substring is a palindrome. Return all such palindromic partitions of s.
Note: A palindrome string is a string that reads the same backward as forward.
=>  PalindromePartitioning.cpp

Find_K-th_smallest_element_in_BST.cpp
Problem statement: Given a binary search tree find the kth largest and smallest element in Binary Search Tree
=> Find K-th smallest element in BST

ReverseWordsInString.cpp
A Program to Reverse the words of string
Example
Input: s=”this is an amazing program”
Output: “program amazing an is this”
=> Program to reverse words in a String

BinaryTreeTraversal.cpp
Program for different Binary Tree Traversal. i.e InOrder ,PreOrder ,PostOrder,
=> Program for different Binary Tree Traversal

DSA in CPP/Array Adt/SelectionSort.cpp
Added a C++ program implementing Selection Sort.
=> Added SelectionSort.cpp

inorderMorrisTraversal.cpp
Problem Statement: Write a program for Morris Inorder Traversal of a Binary Tree.
Solves #89
=> Morris Traversal | solves #89

mooresVotingAlgorithm.cpp
Problem Statement: Given an array of N integers, write a program to return an element that occurs more than N/2 times in the given array. You may consider that such an element always exists in the array.
Solves #91
=> Moore’s Voting Algorithm

Implement_Trie_1.cpp
Problem Statement: Implementing insertion, search, and startWith operations in a trie or prefix-tree.
Implementation: 
Type 1: To insert a string “word” in Trie.                           
Type 2: To check if the string “word” is present in Trie or not.
Type 3: To check if there is any string in the Trie that starts with the given prefix string “word”.
=> Implement_Trie_1.cpp

Insertion-Deletion_Conversion_string.cpp
Minimum Insertions/Deletions to Convert String A to String B
We are given two strings, str1 and str2. We are allowed the following operations:
Delete any number of characters from string str1.
Insert any number of characters in string str1.
We need to tell the minimum operations required to convert str1 to str2.
=> Insertion-Deletion_Conversion_string.cpp

Palindromic_substrings.cpp
// Given a string s, return the number of palindromic substrings in it.  // A string is a palindrome when it reads the same backward as forward. // A substring is a contiguous sequence of characters within the string. // Example 1:
// Input: abc 
// Output: 3 
// Explanation: palindromic substrings are 'a', 'b' ,'c' 
// Example 2:
// Input: aaa 
// Output: 6 
// Explanation: palindromic substrings are 'a', 'a' ,'aa','aa','a','aaa'
=> Palindromic_substrings.cpp

radixSort.cpp
please merge my pull request anad mark it as Hacktoberfest.
=> radixSort Algorithm Hacktoberfest

Disjoint_set.cpp
This is a very simple and beginner friendly implementation of UnionFind/Disjoint Set data structure.
=> Union Find/Disjoint set Implementations

OpenAdressingLinearProbing.cpp
This code conatins a very simple and beginner friendly implementations of how to resolve collisons in Hash tables through Open Adressing using Linear probing.
=> Hash Table Implementation through open adressing method using Linear probing.

inheritance.cpp
Signed-off-by: omkar-mk <83657055+omkar-mk@users.noreply.github.com>
=> inheritance(hacktoberfest 2022)

Factorial.cpp
Hey there!!!
I have included the program to calculate Factorial for a given number.This program uses recursion technique.
=> added the program to calculate Factorial of a given number

Factorial.cpp, NthPermutation.cpp
Hey there!!!
I have included the program for finding kth permutation of a number with n digits.This program directly gives you the kth permutation without having to figure out the rest permutations.
=> Kth permutation of N digit number

Factorial.cpp, NthPermutation.cpp, TreeHeight.cpp
This program helps you find the height of a Tree with the help of it's root node.
=> Tree height

Factorial.cpp, NthPermutation.cpp, TreeDiameter.cpp, TreeHeight.cpp
This program returns you the diameter of the tree.
=> Tree diameter

Dijkstra.cpp
Problem Statement: Given a weighted, undirected, and connected graph of V vertices and E edges, Find the shortest distance of all the vertex’s from the source vertex S.
Note: The Graph doesn’t contain any negative weight cycle.
solves #141
=> Dijkstra’s Algorithm – Shortest distance

Maximum_XOR_of_Two_Numbers_in_an_Array.cpp
Problem Statement: You are given two arrays of non-negative integers say ‘arr1’ and ‘arr2’ of sizes N and M respectively. Find the maximum value of ( ‘A’ xor ‘B’ ) where ‘A’ and ‘B’ are any elements from ‘arr1’ and ‘arr2’ respectively and ‘xor’ represents the bitwise xor operation. Maximum XOR of Two Numbers in an Array.
Example 1:
Input: N=2, M=3
arr1 = [6, 8] 
arr2 = [7, 8, 2]
Output: 15
Explanation: Possible pairs are (6, 7), (6, 8), (6, 2), (8, 7), (8, 8), (6, 2). And 8 xor 7 will give the maximum result i.e. 15
Example 2:
Input: N=2, M=2
arr1 = [1, 2
]
arr2 = [1, 1]
Output: 3
Explanation: 3 is the maximum possible xor among all possible pairs.
Signed-off-by: Pranav Katiyar <pk.pranavkatiyar@gmail.com>
=> Maximum_XOR_of_Two_Numbers_in_an_Array.cpp

Topological_Sort_Algorithm.cpp
Problem Statement: Given a Directed Acyclic Graph (DAG) with V vertices and E edges, Find any Topological Sorting of that Graph.
Input: V = 6, E = 6
Output: 5, 4, 2, 3, 1, 0
Explanation: A graph may have multiple topological sortings.  The result is one of them. The necessary conditions  for the ordering are:
According to edge 5 -> 0, node 5 must appear before node 0 in the ordering. According to edge 4 -> 0, node 4 must appear before node 0 in the ordering. According to edge 5 -> 2, node 5 must appear before node 2 in the ordering. According to edge 2 -> 3, node 2 must appear before node 3 in the ordering. According to edge 3 -> 1, node 3 must appear before node 1 in the ordering. According to edge 4 -> 1, node 4 must appear before node 1 in the ordering.
The above result satisfies all …
=> Topological_Sort_Algorithm.cpp

Rotate_Image_by _90_degree.cpp
Problem Statement: Given a matrix, your task is to rotate the matrix 90 degrees clockwise.
Example 1:
Input: [[1,2,3],[4,5,6],[7,8,9]]
Output: [[7,4,1],[8,5,2],[9,6,3]]
Explanation: Rotate the matrix simply by 90 degree clockwise and return the matrix.
Example 2:
Input: [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
Output:[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]
Explanation: Rotate the matrix simply by 90 degree clockwise and return the matrix.
Signed-off-by: pkpk1987 <90591476+pkpk1987@users.noreply.github.com>
=> Rotate_Image_by _90_degree.cpp

Job_Sequencing_Problem.cpp
Problem Statement: You are given a set of N jobs where each job comes with a deadline and profit. The profit can only be earned upon completing the job within its deadline. Find the number of jobs done and the maximum profit that can be obtained. Each job takes a single unit of time and only one job can be performed at a time.
Example 1:
Input: N = 4, Jobs = {(1,4,20),(2,1,10),(3,1,40),(4,1,30)}
Output: 2 60
Explanation: The 3rd job with a deadline 1 is performed during the first unit of time .The 1st job is performed during the second unit of time as its deadline is 4. Profit = 40 + 20 = 60
Example 2:
Input: N = 5, Jobs = {(1,2,100),(2,1,19),(3,2,27),(4,1,25),(5,1,15)}
Output: 2 127
Explanation: The  first and third job both having a deadline 2 give the highest profit.  Profit = 100 + 27 …
=> Job_Sequencing_Problem.cpp

Fractional_Knapsack_Problem.cpp
Problem Statement: The weight of N items and their corresponding values are given. We have to put these items in a knapsack of weight W such that the total value obtained is maximized.
Example:
Input: N = 3, W = 50, values[] = {100,60,120}, weight[] = {20,10,30}.
Output: 240.00
Explanation: The first and second items  are taken as a whole  while only 20 units of the third item is taken. Total value = 100 + 60 + 80 = 240.00
Signed-off-by: pkpk1987 <90591476+pkpk1987@users.noreply.github.com>
=> Fractional_Knapsack_Problem.cpp

Find_minimum_number_of_coins.cpp
Problem Statement: Given a value V, if we want to make a change for V Rs, and we have an infinite supply of each of the denominations in Indian currency, i.e., we have an infinite supply of { 1, 2, 5, 10, 20, 50, 100, 500, 1000} valued coins/notes, what is the minimum number of coins and/or notes needed to make the change.
Example 1:
Input: V = 70
Output: 2
Explaination: We need a 50 Rs note and a 20 Rs note.
Example 2:
Input: V = 121
Output: 3
Explaination: We need a 100 Rs note, a 20 Rs note and a 1 Rs coin.
Signed-off-by: pkpk1987 <90591476+pkpk1987@users.noreply.github.com>
=> Find_minimum_number_of_coins.cpp

Count_Reverse_Pairs.cpp
Problem Statement: Given an array of numbers, you need to return the count of reverse pairs.  Reverse Pairs are those pairs where i<j and arr[i]>2*arr[j].
Example 1:
Input: N = 5, array[] = {1,3,2,3,1)
Output: 2 
Explanation: The pairs are (3, 1) and (3, 1) as from both the pairs the condition arr[i] > 2*arr[j] is satisfied.
Example 2:
Input: N = 4, array[] = {3,2,1,4}
Output: 1
Explaination: There is only 1 pair  ( 3 , 1 ) that satisfy the condition arr[i] > 2*arr[j]
Signed-off-by: Pranav <73035317+pranavkatiyar28@users.noreply.github.com>
=> Count_Reverse_Pairs.cpp

Check_if_an_Array_is_Sorted.cpp
Problem Statement: Given an array of size n, write a program to check if the given array is sorted in (ascending / Increasing / Non-decreasing) order or not. If the array is sorted then return True, Else return False.
Note: Two consecutive equal values are considered to be sorted.
=> Check_if_an_Array_is_Sorted.cpp

strcpy_in_C.cpp
Problem Statment: Given two Strings copy the contents of one string to another.
=> strcpy_in_C.cpp

Two_stacks_in_an_array.cpp
Problem Statement: You need to try implementing 2 stacks in a single array.
=> Two_stacks_in_an_array.cpp

Word_Search_Leetcode.cpp
Given an m x n grid of characters board and a string word, return true if the word exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.
=> Word_Search_Leetcode.cpp

Container_with_most_water.cpp
Problem Statement:  Given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.
Notice that you may not slant the container.
=> Container_with_most_water.cpp

search_2d_matrix.cpp
Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:
Integers in each row are sorted from left to right. The first integer of each row is greater than the last integer of the previous row.
Signed-off-by: bilwa496 <66560100+bilwa496@users.noreply.github.com>
=> Created search_2d_matrix.cpp

Overlapping_Intervals.cpp
Problem Statement: Given an array of intervals where intervals[i] = [starti, endi], return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.
=> Overlapping_Intervals.cpp

Insert_New_Interval.cpp
Problem Statement: You are given an array of non-overlapping intervals where intervals[i] = [start, end] represent the start and the end of the ith interval, and intervals is sorted in ascending order by start. You are also given an interval newInterval = [start, end] that represents the start and end of another interval. 
Insert newInterval into intervals such that intervals are still sorted in ascending order by start and intervals still do not have any overlapping intervals (merge overlapping intervals if necessary). Return intervals after the insertion. 
=> Insert_New_Interval.cpp

Minimum_Window_substring.cpp
Problem Statement: Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string. 
=> Minimum_Window_substring.cpp

KMP_Algorithm.cpp
Problem Statement: Implement the Knuth-Morris-Pratt KMP string matching algorithm.
=> KMP_Algorithm.cpp

Spiral_Traversal_of_Matrix.cpp
Problem Statement: Given a Matrix, print the given matrix in spiral order.
=> Spiral_Traversal_of_Matrix.cpp

Count_Distinct_Elements_In_Every_Window.cpp
Problem Statement:
“Given an array of integers and a number K. Find the count of distinct elements in every window of size K in the array.”
=> Count_Distinct_Elements_In_Every_Window.cpp

Anagram_Substring_Search.cpp
Problem Statement : Given two Strings let’s say  S and P, return the array of all start indices of P’s anagram in S.
An Anagram is a word or phrase or name formed by rearranging the letters of another word or phrase or name.
Note: S and P contains only Lower Case Letters
=> Anagram_Substring_Search.cpp

Longest_substring_containing_distinct_elements.cpp
Problem Statement: Given a string consisting of alphabetic characters. Print the length of the longest substring containing distinct elements.
=> Longest_substring_containing_distinct_elements.cpp

Leftmost_Repeating_Character_in_a_String.cpp
Problem Statement: Given a string, find the leftmost repeating character of the string. i.e The first character that appeared again in the further string.
=> Leftmost_Repeating_Character_in_a_String.cpp

Naive_pattern_searching.cpp
Problem Statement: “Given a text and a pattern, write a program to print the occurrences of pattern in the text”
=> Naive_pattern_searching.cpp

Two_Odd_Occurring.cpp
Problem Statement: Find the two numbers which occur an odd number of times in the given unsorted array.
=> Two_Odd_Occurring.cpp

Count_Trailing_Zeroes.cpp
Problem Statement: “Given an integer n, return the number of trailing zeroes in n!.
Note that n! = n * (n – 1) * (n – 2) * … * 3 * 2 * 1.”
=> Count_Trailing_Zeroes.cpp

Pairwise_swap_nodes_of_linked_list.cpp
Problem Statement: Given a singly linked list. Your task is to swap all the elements pairwise.
=> Pairwise_swap_nodes_of_linked_list.cpp

Sieve_of_Eratosthenes_Find_all_Prime_Numbers.cpp
Problem Statement: Sieve of Eratosthenes – Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number.
=> Sieve_of_Eratosthenes_Find_all_Prime_Numbers.cpp

Peak_element_in_Array.cpp
Problem Statement: Given an array, find a peak element(print anyone, if many are found). A peak element is one such that it is either greater than or equal to its neighbours. For the first and last element, it is enough to look at its only one neighbour.
=> Peak_element_in_Array.cpp

Matrix_in_Snake_Pattern.cpp
Problem Statement: Given an N x N matrix. Your task is to print the elements of the matrix in the snake pattern.
=> Matrix_in_Snake_Pattern.cpp

Josephus_Problem.cpp
Problem Statement: There are n people standing in a circle waiting to be executed. The counting out begins at some point in the circle and proceeds around the circle in a fixed direction. In each step, a certain number of people are skipped and the next person is executed. The elimination proceeds around the circle (which is becoming smaller and smaller as the executed people are removed), until only the last person remains, who is given freedom. Given the total number of person n and a number k which indicates that k-1 persons are skipped and the kth person is killed in a circle. The task is to choose the place in the initial circle so that you are the last one remaining and so survive. 
=> Josephus_Problem.cpp

Check_if_a_String_is_a_subsequence_of_other.cpp
Problem Statement: Let there are two strings S1 and S2. If the S1 is a subsequence of S2 return true otherwise return false.
String S1 is said to be a subsequence of string S2 if S1 is can be obtained from the S2 by deleting some of the characters from S2 without disturbing the relative positions of the remaining characters in S2.
=> Check_if_a_String_is_a_subsequence_of_other.cpp

Rotate_Matrix_anti-clockwise_by_90_degree.cpp
Problem statement: Given a matrix, your task is to rotate matrix anti-clockwise by 90 degrees.
=> Rotate_Matrix_anti-clockwise_by_90_degree.cpp

Find_word_with_highest number_of_repeated_letters_in_string.cpp
Problem Statement: Write a program to find a word in a given string that has the highest number of repeated letters. If not found, return -1.
=> word_with_most_no_of_repeated_letters.cpp

Reverse a Linked List.cpp
Problem Statement: Given the head of a singly linked list, write a program to reverse the linked list, and return the head pointer to the reversed list.
Input Format: 
head = [3,6,8,10]
This means the given linked list is 3->6->8->10 with head pointer at node 3.
Result:
Output = [10,6,8,3]
This means, after reversal, the list should be 10->6->8->3 with the head pointer at node 10.
Signed-off-by: pkpk1987 <90591476+pkpk1987@users.noreply.github.com>
=> Reverse a Linked List.cpp

Min_Window_substring.cpp
Problem Statement: Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string. 
Signed-off-by: harryusingh <116804092+harryusingh@users.noreply.github.com>
=> Min_Window_substring.cpp

Detect_cycle_in_a_directed_graph_using_DFS.cpp
Problem Statement: Given a directed graph with V vertices and E edges, check whether it contains any cycle or not. 
Signed-off-by: harryusingh <116804092+harryusingh@users.noreply.github.com>
=> Detect_cycle_in_a_directed_graph_using_DFS.cpp

Find_Eventual_Safe_States.cpp
Problem Statement: A directed graph of V vertices and E edges is given in the form of an adjacency list adj. Each node of the graph is labeled with a distinct integer in the range 0 to V – 1. A node is a terminal node if there are no outgoing edges. A node is a safe node if every possible path starting from that node leads to a terminal node. You have to return an array containing all the safe nodes of the graph. The answer should be sorted in ascending order.
Signed-off-by: harryusingh <116804092+harryusingh@users.noreply.github.com>
=> Find_Eventual_Safe_States.cpp

Kahn’s_Algorithm_Topological_Sort_Algorithm.cpp
Problem Statement: Given a Directed Acyclic Graph (DAG) with V vertices and E edges, Find any Topological Sorting of that Graph.
Note: In topological sorting, node u will always appear before node v if there is a directed edge from node u towards node v(u -> v).
Signed-off-by: harryusingh <116804092+harryusingh@users.noreply.github.com>
=> Kahn’s_Algorithm_Topological_Sort_Algorithm.cpp

Vector_Erase.cpp
Problem Statement: You are provided with a vector of  integers. Then, you are given  queries. For the first query, you are provided with  integer, which denotes a position in the vector. The value at this position in the vector needs to be erased. The next query consists of  integers denoting a range of the positions in the vector. The elements which fall under that range should be removed. The second query is performed on the updated vector which we get after performing the first query.
Signed-off-by: Divyanshu Gupta <52619165+divyanshu799@users.noreply.github.com>
=> Vector_Erase.cpp

DSA in CPP/Array Adt/SelectionSort.cpp, MatrixToSpiralMatrix.cpp, Wildcard_Pattern_Matching.cpp, minimum partition.cpp
If you find my code interesting please accept my pull request
=> added few cpp codes

Left_Rotate_the_Array_by_One.cpp
Problem Statement: Given an array of N integers, left rotate the array by one place.
=> Left_Rotate_the_Array_by_One.cpp

Remove_brackets_from_an_algebraic_expression.cpp
Problem Statement: Remove brackets from an algebraic expression
=> Remove_brackets_from_an_algebraic_expression.cpp

Finding_Equilibrium_index_in_an_array.cpp
Problem Statement: Finding Equilibrium index in an array
=> Finding_Equilibrium_index_in_an_array.cpp

Implement_Trie – II.cpp
Problem Statement:  Implement a data structure ”TRIE” from scratch. Complete some functions.
=> Implement_Trie – II.cpp

Fractional_Knapsack_Problem_Greedy_Approach.cpp
Problem Statement: The weight of N items and their corresponding values are given. We have to put these items in a knapsack of weight W such that the total value obtained is maximized.
=> Fractional_Knapsack_Problem_Greedy_Approach.cpp

M – Coloring_Problem.cpp
Problem Statement: Given an undirected graph and a number m, determine if the graph can be colored with at most m colors such that no two adjacent vertices of the graph are colored with the same color.
=> M – Coloring_Problem.cpp

Rotate_Image_by_90_degree.cpp
Problem Statement: Given a matrix, your task is to rotate the matrix 90 degrees clockwise.
=> Rotate_Image_by_90_degree.cpp

Implement_LRU_Cache.cpp
Problem Statement: “Design a data structure that follows the constraints of Least Recently Used (LRU) cache”.
=> Implement_LRU_Cache.cpp

Minimum_number_of_platforms_required_for_a_railway.cpp
Problem Statement: We are given two arrays that represent the arrival and departure times of trains that stop at the platform. We need to find the minimum number of platforms needed at the railway station so that no train has to wait.
=> Min_number_of_platforms_required_for_a_railway.cpp

Morris_Inorder_Traversal_of_a_Binary_tree.cpp
Problem Statement: Write a program for Morris Inorder Traversal of a Binary Tree.
=> Morris_Inorder_Traversal_of_a_Binary_tree.cpp

Find the Majority Element that occurs more than N divided by 2 times.cpp
Problem Statement: Given an array of N integers, write a program to return an element that occurs more than N/2 times in the given array. You may consider that such an element always exists in the array.
=> Element that occurs more than N/2  times.cpp

Implement_Stack_using_Array.cpp
Problem statement: Implement a stack using an array.
Explanation: 
push(): Insert the element in the stack.
pop(): Remove and return the topmost element of the stack.
top(): Return the topmost element of the stack
size(): Return the number of remaining elements in the stack.
Signed-off-by: Pranav <73035317+pranavkatiyar28@users.noreply.github.com>
=> Implement_Stack_using_Array.cpp

Kahn’s_Algorithm.cpp
Problem Statement: Given a Directed Acyclic Graph (DAG) with V vertices and E edges, Find any Topological Sorting of that Graph.
Input Format: V = 6, E = 6
Result: 5, 4, 0, 2, 3, 1
Explanation: A graph may have multiple topological sortings.  The result is one of them. The necessary conditions for the ordering are: According to edge 5 -> 0, node 5 must appear before node 0 in the ordering. According to edge 4 -> 0, node 4 must appear before node 0 in the ordering. According to edge 5 -> 2, node 5 must appear before node 2 in the ordering. According to edge 2 -> 3, node 2 must appear before node 3 in the ordering. According to edge 3 -> 1, node 3 must appear before node 1 in the ordering. According to edge 4 -> 1, node 4 must appear before node 1 in the ordering.
The above result satisfies …
=> Kahn’s_Algorithm.cpp

Eventual_Safe_States.cpp
Problem Statement: A directed graph of V vertices and E edges is given in the form of an adjacency list adj. Each node of the graph is labeled with a distinct integer in the range 0 to V – 1. A node is a terminal node if there are no outgoing edges. A node is a safe node if every possible path starting from that node leads to a terminal node. You have to return an array containing all the safe nodes of the graph. The answer should be sorted in ascending order.
Signed-off-by: Abhirup Roy <40180841+amiableabhi01@users.noreply.github.com>
=> Eventual_Safe_States.cpp

Counting_Bits.cpp
Problem statement : Given an integer n, return an array ans whose length is n+1 such that for each i (0 <= i <= n) ans[i] is the number of 1’s in binary representation of i. 
Signed-off-by: Abhirup Roy <40180841+amiableabhi01@users.noreply.github.com>
=> Counting_Bits.cpp

Minimum_in_Rotated_Sorted_Array.cpp
Problem Statement: Suppose an array of length n sorted in ascending order is rotated between 1 and n times. For example, the array nums[] = [0,1,2,4,5,6,7] might become:
[4,5,6,7,0,1,2] if it was rotated 4 times.
[0,1,2,4,5,6,7] if it was rotated 7 times.
Given the sorted rotated array nums of unique elements, return the minimum element of this array.
Signed-off-by: Abhirup Roy <40180841+amiableabhi01@users.noreply.github.com>
=> Minimum_in_Rotated_Sorted_Array.cpp

Merge_k_Sorted_Arrays.cpp
Problem Statement: You are given an array of k linked-lists lists, each linked list is sorted in ascending order. You need to merge all the linked list into a single linked list and return it.
Signed-off-by: Abhirup Roy <40180841+amiableabhi01@users.noreply.github.com>
=> Merge_k_Sorted_Arrays.cpp

Wildcard_Matching.cpp
Problem Statement: Wildcard Matching
We are given two strings ‘S1’ and ‘S2’. String S1 can have the following two special characters:
‘?’ can be matched to a single character of S2.
‘*’ can be matched to any sequence of characters of S2. (sequence can be of length zero or more). We need to check whether strings S1 and S2 match or not.
Signed-off-by: Anuj Chaudhary <42280986+Anuj-Chaudhary@users.noreply.github.com>
=> Wildcard_Matching.cpp
